### ISSUE TITLE
Deploy TRAPI 1.3

### ISSUE THREAD

**Issue by capasfield** [webyrd/mediKanren#101]
Here's your official ticket:
"https://arax.ncats.io/?smartapi=1 shows that mediKanren  has 1.1 in development (infores:unsecret-agent). Please deploy 1.3 of this tool into development ASAP."

Tickets were created for all tools that do not currently have 1.3 in development. We know you are rebuilding the tool and making tremendous progress. But we would be remiss if we didn't keep you in the loop that we're moving to 1.3. Please keep us posted and keep on trucking.

**Comment by webyrd** [comment]
Thank you!  Yes the new server will support TRAPI 1.3

Cheers,

--Will
