### ISSUE TITLE
Chembl prefix being used

### ISSUE THREAD

**Issue by MarkDWilliams** [webyrd/mediKanren#44]
Queries sent to Unsecret agent return compounds from chembl with the "chembl" prefix rather than that "chembl.compound" prefix that is in TRAPI.

**Comment by MarkDWilliams** [comment]
Adding an example query that returns compounds with this prefix:
`{
  "message": {
    "query_graph": {
      "edges": [
        {
          "id": "e00",
          "source_id": "n00",
          "target_id": "n01",
          "type": "treated_by"
        }
      ],
      "nodes": [
        {
          "curie": "MONDO:0021668",
          "id": "n00",
          "type": "disease"
        },
        {
          "id": "n01",
          "type": "chemical_substance"
        }
      ]
    }
  }
}`

and an example of the chembl prefix being returned
`
id: "ChEMBL:CHEMBL1077",
name: "Bromfenac",
type: "chemical_substance"
`

**Comment by gregr** [comment]
Looks like those results are coming from MolePro.
