### ISSUE TITLE
A bunch of semi-related tasks to help transition to mediKanren 2 

### ISSUE THREAD

**Issue by webyrd** [webyrd/mediKanren#60]
Since we are moving to mediKanren 2, there are a bunch of related things to do:

* port the webserver to mediKanren 2

* implement TRAPI 1.1 compliance for the May Relay

* augment our server with “pragma” style directives that extend TRAPI, so we can do reasoning that TRAPI doesn’t currently support, but which is useful to PMI use cases

* implement the ability for TRAPI requests to span multiple KGs

* implement light weight reasoning / query expansion

* implement / improve node and edge normalization

* make sure the NCATS TRAPI queries we are getting don’t break or DoS the server, and return reasonable answers

**Comment by jeffhhk** [comment]
Broken out separately into #62 through #71.

@webyrd  Please close.  I do not have permission to do so.
